env: "local"

http_server:
  host: "localhost"
  port: 3000

postgres:
  master:
    host: "localhost"
    port: "5432"
    user: "postgres"
    password: "123"
    db: "wms"
    max_open_connections: 100
    max_idle_connections: 10
    conn_max_lifetime: "1h"
    debug_mode: true
    prepare_stmt: true
    skip_default_transaction: false

  slaves:
    count: 2
    
    slave_1:
      host: "localhost"
      port: "5433"  
      user: "postgres"
      password: "123"
      db: "wms"
      max_open_connections: 50
      max_idle_connections: 5
      conn_max_lifetime: "1h"
      debug_mode: false
      prepare_stmt: true
      skip_default_transaction: false

    slave_2:
      host: "localhost"
      port: "5434"  
      user: "postgres"
      password: "123"
      db: "wms"
      max_open_connections: 50
      max_idle_connections: 5
      conn_max_lifetime: "1h"
      debug_mode: false
      prepare_stmt: true
      skip_default_transaction: false

aws:
  region: "us-east-1"
  account: "000000000000"
  shouldLog: true
  sqs:
    prefix: "local"
    endpoint: "http://localhost:4566"

redis_addr: "redis://:redispassword@localhost:6379/"
kafka_broker: "localhost:9092"
sqs_queue_url: "http://localhost:4566/000000000000/bulk-orders-queue"

